# Generated by Django 3.1.1 on 2020-09-19 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='description',
            field=models.TextField(verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='icon_img',
            field=models.CharField(blank=True, max_length=100, verbose_name='icon_img'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='title',
            field=models.CharField(max_length=50, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='type',
            field=models.IntegerField(blank=True, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='userchallenge',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date'),
        ),
    ]
