# Generated by Django 2.2.16 on 2020-09-17 06:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Forestbook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='NAME')),
                ('fullname', models.CharField(max_length=100, verbose_name='FULLNAME')),
                ('species', models.CharField(max_length=20, verbose_name='SPECIES')),
                ('description', models.TextField(verbose_name='DESCRIPTION')),
                ('type', models.IntegerField(blank=True, verbose_name='TYPE')),
                ('habitat', models.CharField(max_length=20, verbose_name='HABITAT')),
                ('season', models.IntegerField(blank=True, verbose_name='SEASON')),
                ('img', models.CharField(blank=True, max_length=100, verbose_name='IMG')),
            ],
        ),
        migrations.CreateModel(
            name='Userbook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='DATE')),
                ('img', models.CharField(blank=True, max_length=100, verbose_name='IMG')),
                ('forestbook_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forestbook.Forestbook')),
                ('userinfo_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='')),
            ],
        ),
    ]
