# Generated by Django 3.1.1 on 2020-10-01 13:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Forestbook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='name')),
                ('eng_name', models.CharField(max_length=30, verbose_name='eng_name')),
                ('sympolism', models.CharField(max_length=30, verbose_name='sympolism')),
                ('description', models.TextField(verbose_name='description')),
                ('use', models.TextField(verbose_name='use')),
                ('growth', models.TextField(verbose_name='growth')),
                ('season', models.CharField(max_length=20, verbose_name='season')),
                ('img', models.ImageField(default=None, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Userbook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='date')),
                ('img', models.ImageField(default=None, upload_to='')),
                ('forestbook_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='forestbook.forestbook', verbose_name='forestbook_id')),
                ('userinfo_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='userinfo_id')),
            ],
        ),
    ]
