# Generated by Django 3.1.1 on 2020-09-28 02:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Forestbook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='name')),
                ('fullname', models.CharField(max_length=100, verbose_name='fullname')),
                ('species', models.CharField(max_length=20, verbose_name='species')),
                ('description', models.TextField(verbose_name='description')),
                ('type', models.IntegerField(blank=True, verbose_name='type')),
                ('habitat', models.CharField(max_length=20, verbose_name='habitat')),
                ('season', models.IntegerField(blank=True, verbose_name='season')),
                ('img', models.ImageField(default=None, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Userbook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='date')),
                ('img', models.ImageField(default=None, upload_to='')),
                ('forestbook_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forestbook.forestbook')),
                ('userinfo_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='')),
            ],
        ),
    ]
