# Generated by Django 3.1.1 on 2020-09-22 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forestbook', '0002_auto_20200919_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forestbook',
            name='img',
            field=models.ImageField(default=None, upload_to=''),
        ),
        migrations.AlterField(
            model_name='userbook',
            name='img',
            field=models.ImageField(default=None, upload_to=''),
        ),
    ]
