# Generated by Django 3.1.1 on 2020-09-24 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_auto_20200924_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='detail',
            field=models.TextField(default='', verbose_name='detail'),
        ),
        migrations.AddField(
            model_name='article',
            name='title',
            field=models.CharField(default='', max_length=20, verbose_name='title'),
        ),
    ]
